create table if not exists word
(
    id    integer primary key not null generated by default as identity,
    value text
);
create index if not exists word_idx ON word (value);

create table if not exists url
(
    id    integer primary key not null generated by default as identity,
    value text
);
create index if not exists url_idx ON url (value);

create table if not exists location
(
    id       integer primary key not null generated by default as identity,
    url_id   integer references url (id) on delete cascade,
    word_id  integer references word (id) on delete cascade,
    position integer
);
create index if not exists word_location_idx ON location(word_id);

create table if not exists link_between_url
(
    id          integer primary key not null generated by default as identity,
    from_url_id integer references url (id) on delete cascade,
    to_url_id   integer references url (id) on delete cascade
);
create index if not exists url_to_idx ON link_between_url(to_url_id);
create index if not exists url_from_idx ON link_between_url(from_url_id);

create table if not exists page_rank
(
    id     integer primary key not null generated by default as identity,
    url_id integer references url (id) on delete cascade,
    score  real
);
create index if not exists rank_url_id_idx ON page_rank(url_id);










